# Generated by Django 4.1.7 on 2023-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('price', models.FloatField(verbose_name='price')),
                ('description', models.TextField(verbose_name='description')),
                ('address', models.TextField(verbose_name='address')),
                ('is_published', models.BooleanField(verbose_name='is_published')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64, unique=True, verbose_name='name')),
            ],
        ),
    ]
